### ISSUE TITLE
Version 2.11.0 fails to start

### ISSUE THREAD

**Issue by gamblen** [Particular/ServiceInsight#1295]
**Symptoms**
After upgrading to v2.11.0 the application fails to start.  There are entries in the Windows Event Viewer

Application: ServiceInsight.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoad(System.String, System.Security.Policy.Evidence, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoad(System.String, System.Security.Policy.Evidence, System.Threading.StackCrawlMark ByRef, Boolean)
   at System.Reflection.Assembly.Load(System.String)
   at DevExpress.Utils.AssemblyHelper.GetAssembly(System.String, System.Func`2<System.String,System.Reflection.Assembly>)
   at DevExpress.Xpf.Core.Theme.get_Assembly()
   at DevExpress.Xpf.Core.ThemedElementsDictionary.GetThemeAssembly(System.String)
   at DevExpress.Xpf.Core.ThemedElementsDictionary.ForceThemeKeysLoading(System.String)
   at DevExpress.Xpf.Core.ThemeManager.ForceThemeKeyCreating(System.String)
   at DevExpress.Xpf.Core.ThemeManager.ChangeTheme(System.Windows.DependencyObject, System.String, Boolean, Boolean, Boolean)
   at DevExpress.Xpf.Core.ThemeManager.ThemeNamePropertyChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at System.Windows.DependencyObject.SetCurrentValue(System.Windows.DependencyProperty, System.Object)
   at DevExpress.Xpf.Utils.Themes.GlobalThemeHelper.AssignApplicationThemeName(System.Windows.Window)
   at DevExpress.Xpf.Utils.Themes.WindowTracker.DoWork(System.Object)
   at System.Windows.PropertyChangedCallback.Invoke(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(System.Object, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(System.Object, System.Xaml.XamlMember, System.Object)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at ServiceInsight.Shell.AboutView.AsSplashScreen()
   at DevExpress.Xpf.Core.DXSplashScreen+SplashScreenContainer.InternalThreadEntryPoint(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)

and 

Faulting application name: ServiceInsight.exe, version: 2.11.0.0, time stamp: 0xe20a0cc7
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2193, time stamp: 0x7f7062e1
Exception code: 0xe0434352
Fault offset: 0x000000000002cd29
Faulting process ID: 0x7ad4
Faulting application start time: 0x01d90a15b409d715
Faulting application path: C:\Program Files (x86)\Particular Software\ServiceInsight\ServiceInsight.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 0a8a17bb-783b-4d05-ad55-73953a3f2bcb
Faulting package full name: 
Faulting package-relative application ID:

**Comment by HEskandari** [comment]
@gamblen thanks for the report. We are looking into it.

**Comment by cquirosj** [comment]
This bug has been addressed in [PR 1296](https://github.com/Particular/ServiceInsight/pull/1296). Closing.

**Comment by cquirosj** [comment]
Version [2.12.0](https://github.com/Particular/ServiceInsight/releases/tag/2.12.0) fixes this issue and is now available for download.

**Comment by gamblen** [comment]
@cquirosj confirmed.  All working.  Thank you.
