### ISSUE TITLE
Exception message in ServiceInsight can be better

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceInsight#347]
Right now, for exceptions, we get a dialog with a big **`Oops`**

![image](https://cloud.githubusercontent.com/assets/854553/3368849/45bee984-fb7a-11e3-8973-4ae49baf9c51.png)

**Exception Details**

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Particular.ServiceInsight.Desktop.Models.StoredMessage.DisplayPropertiesChanged(StoredMessage focusedMessage) in y:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\Models\StoredMessage.cs:line 139
   at Particular.ServiceInsight.Desktop.MessageList.MessageListViewModel.ShouldUpdateMessage(StoredMessage focusedMessage, StoredMessage newMessage) in y:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\MessageList\MessageListViewModel.cs:line 310
   at Particular.ServiceInsight.Desktop.MessageList.MessageListViewModel.<>c__DisplayClass10.<ShouldUpdateMessages>b__e(StoredMessage message) in y:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\MessageList\MessageListViewModel.cs:line 303
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Particular.ServiceInsight.Desktop.MessageList.MessageListViewModel.ShouldUpdateMessages(PagedResult`1 pagedResult) in y:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\MessageList\MessageListViewModel.cs:line 303
   at Particular.ServiceInsight.Desktop.MessageList.MessageListViewModel.TryRebindMessageList(PagedResult`1 pagedResult) in y:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\MessageList\MessageListViewModel.cs:line 266
   at Particular.ServiceInsight.Desktop.MessageList.MessageListViewModel.RefreshMessages(Endpoint endpoint, Int32 pageIndex, String searchQuery, String orderBy, Boolean ascending) in y:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\MessageList\MessageListViewModel.cs:line 193
   at Particular.ServiceInsight.Desktop.MessageList.MessageListViewModel.RefreshMessages(String orderBy, Boolean ascending) in y:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\MessageList\MessageListViewModel.cs:line 151
   at Particular.ServiceInsight.Desktop.Shell.ShellViewModel.RefreshAll() in y:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\Shell\ShellViewModel.cs:line 208
   at Particular.ServiceInsight.Desktop.Shell.ShellViewModel.OnAutoRefreshing() in y:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\Shell\ShellViewModel.cs:line 256
   at Particular.ServiceInsight.Desktop.Shell.ShellViewModel.<InitializeAutoRefreshTimer>b__11(Object s, EventArgs e) in y:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\Shell\ShellViewModel.cs:line 237
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by johnsimons** [comment]
@indualagarsamy how about we start by:
- removing oops
- reducing the font of the buttons

How does this sound ?

**Comment by indualagarsamy** [comment]
Also:
Instead of `Something went wrong`, How about:
`An exception occurred while we attempted to perform your requested operation`

Instead of `Please report this error and someone will take a look at it`
`Thank you for your time in reporting this error to us, It will help us investigate this error and fix it for all our users.`
