### ISSUE TITLE
Exception when opening ServiceInsight

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServiceInsight#426]
Hi

I keep getting this exception when i open ServiceInsight (1.2.4):

System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Particular.ServiceInsight.Desktop.MessageFlow.MessageFlowViewModel.LinkConversationNodes(IEnumerable`1 relatedMessagesTask) in c:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\MessageFlow\MessageFlowViewModel.cs:line 240
   at Particular.ServiceInsight.Desktop.MessageFlow.MessageFlowViewModel.Handle(SelectedMessageChanged event) in c:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\MessageFlow\MessageFlowViewModel.cs:line 175

![image](https://cloud.githubusercontent.com/assets/8087733/5797305/95972084-9fb7-11e4-8305-59c34a75820c.png)

**Comment by cjoergensen** [comment]
This is possible the same as #415 is there an fix or workaround?

**Comment by distantcam** [comment]
Possibly. I'll try to push out 1.2.5 this week, so you can see if it helps.

**Comment by distantcam** [comment]
@cjoergensen Are you still having this problem with 1.2.5?

**Comment by cjoergensen** [comment]
Hi! I can not reproduce this error in 1.2.5
