### ISSUE TITLE
ServiceInsight 1.2.7 Crashes on Startup

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServiceInsight#445]
ServiceInsight 1.2.7 crashes immediately on Startup:

System.ArgumentException: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Particular.ServiceInsight.Desktop.SequenceDiagram.SequenceDiagramViewModel.CreateMessages(IEnumerable`1 messages) in c:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\SequenceDiagram\SequenceDiagramViewModel.cs:line 154
   at Particular.ServiceInsight.Desktop.SequenceDiagram.SequenceDiagramViewModel.Handle(SelectedMessageChanged message) in c:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\SequenceDiagram\SequenceDiagramViewModel.cs:line 94

**Comment by indualagarsamy** [comment]
hey @cjoergensen - thanks. We'll look into this and get back to you with an update.

**Comment by indualagarsamy** [comment]
@cjoergensen - I updated my copy of ServiceInsight to `1.2.7` and I am not able to reproduce this. The sequence diagram loads fine. Can you uninstall your current version and download the latest from here:
https://github.com/Particular/ServiceInsight/releases/tag/1.2.7
If this still occurs, it could perhaps be related to the data and we can continue to debug. Thanks.

**Comment by cjoergensen** [comment]
@indualagarsamy - I tried downgraded til 1.2.6 an that works fine. And i just upgraded to 1.2.7 again and it crashes on startup. I have reported the error through the "Oops window", but let me know if you need any data from me.


![image](https://cloud.githubusercontent.com/assets/8087733/7459698/1b04e8d0-f29e-11e4-878a-60292adb0ad0.png)

**Comment by distantcam** [comment]
@cjoergensen Would it be possible to get a copy of your ServiceControl database? My email is cameron.macfarland(at)particular.net. Thanks

**Comment by cjoergensen** [comment]
@distantcam Sure no problem. Details should be in your inbox shortly.

**Comment by johnsimons** [comment]
Fixed as part of https://github.com/Particular/ServiceInsight/commit/010e433042bcd93edb5287ce0f528b5a6405c472
