### ISSUE TITLE
Refresh with no SC running crashes SI

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceInsight#468]
```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=ServiceInsight
  StackTrace:
       at Particular.ServiceInsight.Desktop.ServiceControl.DefaultServiceControl.Search(String searchQuery, Int32 pageIndex, String orderBy, Boolean ascending) in c:\Code\ServiceInsight\src\ServiceInsight\ServiceControl\DefaultServiceControl.cs:line 99
       at Particular.ServiceInsight.Desktop.MessageList.MessageListViewModel.RefreshMessages(Endpoint endpoint, Int32 pageIndex, String searchQuery, String orderBy, Boolean ascending) in c:\Code\ServiceInsight\src\ServiceInsight\MessageList\MessageListViewModel.cs:line 170
       at Particular.ServiceInsight.Desktop.Search.SearchBarViewModel.RefreshResult() in c:\Code\ServiceInsight\src\ServiceInsight\Search\SearchBarViewModel.cs:line 109
  InnerException: 
```

![nullref](https://cloud.githubusercontent.com/assets/122666/8072853/bcfb59e8-0f5f-11e5-9e34-01e1a3ff7008.png)

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServiceInsight/commit/d7470d9e790514ee0c16762217f15ad012afd9c5
