### ISSUE TITLE
Invalid cast exception when viewing message body

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#481]
There's an unhandled exception in SI when viewing a failed message body. Here's the stack trace:

```
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Tuple`2[System.String,System.String]'.
at Particular.ServiceInsight.Desktop.ServiceControl.DefaultServiceControl.Execute[T](RestRequestWithCache request, Func`2 selector, String baseUrl) in c:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\ServiceControl\DefaultServiceControl.cs:line 257
at Particular.ServiceInsight.Desktop.ServiceControl.DefaultServiceControl.LoadBody(StoredMessage message) in c:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\ServiceControl\DefaultServiceControl.cs:line 164
at Particular.ServiceInsight.Desktop.MessageList.MessageListViewModel.LoadMessageBody() in c:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\MessageList\MessageListViewModel.cs:line 305
at Particular.ServiceInsight.Desktop.MessageList.MessageListViewModel.DoFocusedRowChanged() in c:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\MessageList\MessageListViewModel.cs:line 108
at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
at System.Reactive.Linq.ObservableImpl.Throttle`1._.Propagate(IScheduler self, UInt64 currentid)
at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass6`1.<Schedule>b__3(Object s, EventArgs e)
at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by HEskandari** [comment]
Fixed in https://github.com/Particular/ServiceInsight/commit/4c4ad22146a2fa50b45d4c30fe6548abc6d89a1b
