### ISSUE TITLE
Message that don't have Receiving endpoints renders properly in SequenceDiagram

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#489]
## Who's affected

* Users doing integration with MSMQ directly where the message is then consumed by NServiceBus / ServiceControl and eventually displayed in ServiceInsight.

## Symptoms

If a message doesn't have a Receiving endpoint address, when displayed in ServiceInsight sequence diagram it throws a NullReferenceException.

**Comment by weralabaj** [comment]
When/how does that happen?

**Comment by HEskandari** [comment]
It happens when the SLR can't find the address of the faulting endpoint. Maybe @johnsimons knows when/how this can happen? Here's the stack trace:

``` 
System.Exception: Could not find address
   at NServiceBus.SecondLevelRetries.Helpers.TransportMessageHelpers.GetAddressOfFaultingEndpoint(TransportMessage message) in y:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\SecondLevelRetries\Helpers\TransportMessageHelpers.cs:line 21
   at NServiceBus.SecondLevelRetries.SecondLevelRetriesProcessor.Defer(TimeSpan defer, TransportMessage message) in y:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\SecondLevelRetries\SecondLevelRetriesProcessor.cs:line 74
   at NServiceBus.SecondLevelRetries.SecondLevelRetriesProcessor.Handle(TransportMessage message) in y:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\SecondLevelRetries\SecondLevelRetriesProcessor.cs:line 53
   at NServiceBus.Satellites.SatelliteLauncher.HandleMessageReceived(Object sender, TransportMessageReceivedEventArgs e, ISatellite satellite) in y:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Satellites\SatelliteLauncher.cs:line 92
   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg) in y:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 453   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message) in y:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 390
   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message) in y:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 260
   at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action() in y:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 238
