### ISSUE TITLE
ServiceInsight crashes on property search for "2018-08-30 08:02:57" in Message Properties table

### ISSUE THREAD

**Issue by dvdstelt** [Particular/ServiceInsight#810]
## Problem Description

Random message, I search properties for the value `2018-08-30 08:02:57` in `Message Properties` table and it immediately reports the following error.

> DevExpress.Data.Filtering.Exceptions.InvalidPropertyPathException: Can't find property 'DxFts_02'
   at DevExpress.Data.Filtering.Helpers.EvaluatorCriteriaValidator.Visit(OperandProperty theOperand)
   at DevExpress.Data.Filtering.Helpers.EvaluatorCriteriaValidator.Validate(IList operands)
   at DevExpress.Data.Filtering.Helpers.EvaluatorCriteriaValidator.Validate(IList operands)
   at DevExpress.Data.Filtering.Helpers.ExpressionEvaluator..ctor(PropertyDescriptorCollection properties, CriteriaOperator criteria, Boolean caseSensitive, Boolean doCreateEvauluatorCore)
   at DevExpress.Xpf.PropertyGrid.Internal.DataViewBase.get_ExpressionEvaluator()
   at DevExpress.Xpf.PropertyGrid.Internal.DataViewBase.IsVisible(RowHandle handle)
   at DevExpress.Xpf.PropertyGrid.Internal.DataViewBase.<GetFilteredChildrenInternal>d__25.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at DevExpress.Xpf.PropertyGrid.Internal.DataViewBase.CanExpand(RowHandle handle)
   at DevExpress.Xpf.PropertyGrid.Internal.RowDataGenerator.PrepareRowDataForHandleOverride(RowDataBase data, RowHandle handle, RowDataProperties properties)
   at DevExpress.Xpf.PropertyGrid.Internal.RowDataGenerator.InitializeViewItemsSource(PropertyGridView view)
   at DevExpress.Xpf.PropertyGrid.Internal.RowDataGenerator.DoActionAndSaveFocus(Action action)
   at DevExpress.Xpf.PropertyGrid.Internal.RowDataGenerator.ImmediateInvalidate(String fieldName)
   at DevExpress.Xpf.PropertyGrid.PropertyGridView.<Invalidate>b__95(FieldNameAction theAction)
   at DevExpress.Xpf.PropertyGrid.Internal.AggregateAction.DevExpress.Xpf.Editors.IAction.Execute()
   at DevExpress.Xpf.Editors.ImmediateActionsManager.<ExecuteActions>b__0()
   at DevExpress.Xpf.Core.Locker.DoLockedAction(Action action)
   at DevExpress.Xpf.Editors.ImmediateActionsManager.ExecuteActions()
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by HEskandari** [comment]
This is almost identical to https://github.com/Particular/ServiceInsight/issues/733 which was fixed [here](https://github.com/Particular/ServiceInsight/pull/740).

Does this happen consistently? Can you give us a repro?

**Comment by dvdstelt** [comment]
It works with any message.

![sc-bug](https://user-images.githubusercontent.com/1257410/44897426-ebf0dd80-acfb-11e8-8071-999444c18515.gif)

**Comment by HEskandari** [comment]
@dvdstelt Thanks, that makes it much more clear.
