### ISSUE TITLE
Invalid JSON string

### ISSUE THREAD

**Issue by markgould** [Particular/ServiceInsight#819]
Started getting the below error on one of my ServiceControl instances. When browsing to the URL, there is no content at all, hence the error.

Anything I can do to help debug this issue? Most messages seem to be ok, it appears to be when it's getting saga information.

```
2019-02-12 07:21:38.219 -06:00 [Information] HTTP GET http://localhost:33333/api/sagas/06f40da3-35cc-473f-9aaf-a9f2003a206b (IfNotModified)

2019-02-12 07:21:38.235 -06:00 [Error] Error executing the request: Invalid JSON string, Status code is OK
System.Runtime.Serialization.SerializationException: Invalid JSON string
   at RestSharp.SimpleJson.DeserializeObject(String json)
   at ServiceInsight.Framework.MessageDecoders.JsonMessageDeserializer.FindRoot(String content) in C:\BuildAgent\work\9a5d3620b7071330\src\ServiceInsight\Framework\MessageDecoders\JsonMessageDeserializer.cs:line 66
   at ServiceInsight.Framework.MessageDecoders.JsonMessageDeserializer.Deserialize[T](IRestResponse response) in C:\BuildAgent\work\9a5d3620b7071330\src\ServiceInsight\Framework\MessageDecoders\JsonMessageDeserializer.cs:line 53
   at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)

```

**Comment by WilliamBZA** [comment]
@markgould Is it possible for you to post the JSON that is being returned here?

**Comment by HEskandari** [comment]
@markgould Did I get this correctly that this is a ServiceControl issue? The right place for it would be [here](https://github.com/Particular/ServiceControl/).

**Comment by markgould** [comment]
@WilliamBZA  - there is no JSON, it's blank

@HEskandari I am not sure. I don't know if it's ever expected for ServiceControl to return empty content. If it's not then yes, I can create an issue on the SC repo.

**Comment by HEskandari** [comment]
@markgould AFAIK ServiceControl should not send back empty content. It could be that the data is removed by the set retention policy, although I don't think in that case you'd get a 200 status code.

Would you be able to send the SC database to us to have a closer look? If you can open a support case by sending an email to support at particular dot net, I can advise how.

**Comment by HEskandari** [comment]
@markgould Just an update that I managed to reproduce this. This can happen if you are not running the Saga Audit plugin which you don't have to. I aim to fix it in one of the next releases.

**Comment by markgould** [comment]
Glad you were able to reproduce it! We have the Saga Audit plugin turned off in production, so that explains why we're seeing it.
