### ISSUE TITLE
ServiceInsight crashes if user has a perpetual license

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#947]
If user has a perpetual license (where we check for release date of the package), the application crash after launch. The exception thrown is this:

```
System.Exception: No ReleaseDateAttribute could be found in assembly, please make sure GitVersion is enabled
   at Particular.Licensing.ReleaseDateReader.GetReleaseDate()
   at Particular.Licensing.License.<>c.<.ctor>b__0_0()
   at Particular.Licensing.License.GetLicenseStatus()
   at Particular.Licensing.License.HasExpired()
   at Particular.Licensing.LicenseSourceResult.<>c.<DetermineBestLicenseSourceResult>b__12_3(LicenseSourceResult p)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Particular.Licensing.LicenseSourceResult.DetermineBestLicenseSourceResult(LicenseSourceResult[] sourceResults)
   at Particular.Licensing.LicenseSourceHKLMRegKey.Find(String applicationName)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Particular.Licensing.ActiveLicense.Find(String applicationName, LicenseSource[] licenseSources)
   at ServiceInsight.Framework.Licensing.AppLicenseManager..ctor()
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
```

This is broken since version `1.15.0` where we moved the licensing package to a separate project.

**Comment by HEskandari** [comment]
Resolved via #946
