### ISSUE TITLE
Can't create own plugin with a reference to "Azure.Storage.Blobs" v12

### ISSUE THREAD

**Issue by JSCProjects** [Particular/ServiceInsight#999]
When I write a plugin with a reference to the new Azure.Storage.Blobs sdk I get the following exception

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.4.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.4.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Azure.Core.Pipeline.ClientDiagnostics..ctor(String clientNamespace, Boolean isActivityEnabled)
   at Azure.Storage.Blobs.BlobContainerClient..ctor(String connectionString, String blobContainerName, BlobClientOptions options)
```

**Comment by HEskandari** [comment]
@JSCProjects thanks for reporting this. Would you be able to reach to us at support at particular and send your plugin so I can investigate this in more depth?
